name: e_chart
description: A chart Flutter project.
version: 0.0.1
homepage: https://github.com/Go-oG/e_chart

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  vector_math: ^2.1.4
  stack_trace: ^1.11.1
  dart_dagre: ^1.0.0
  ml_linalg: ^13.12.6
  scidart: ^0.0.2-dev.12
  collection: ^1.19.0
  #统计相关的
  statistics: ^1.1.3

dependency_overrides:
  #stack_trace: ^1.11.1
  collection: '1.19.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


