import 'package:e_chart/e_chart.dart';

class YAxis extends GridAxis {
  const YAxis({
    super.show,
    super.alignTicks,
    super.position = Align2.start,
    super.type,
    super.offset,
    super.inverse,
    super.min,
    super.max,
    super.splitNumber,
    super.minInterval,
    super.maxInterval,
    super.logBase,
    super.categoryList,
    super.categoryCenter,
    super.timeRange,
    super.timeType,
    super.interval,
    super.axisName,
    super.axisLine,
    super.axisLabel,
    super.splitLine,
    super.splitArea,
    super.axisTick,
    super.axisPointer,
  });

  @override
  YAxis copy({
    Align2? position,
    double? offset,
    bool? show,
    AxisType? type,
    List<String>? categoryList,
    bool? categoryCenter,
    bool? alignTicks,
    TimeType? timeType,
    Pair<DateTime, DateTime>? timeRange,
    num? min,
    num? max,
    int? splitNumber,
    num? minInterval,
    num? maxInterval,
    num? interval,
    int? logBase,
    bool? inverse,
    AxisName? axisName,
    AxisLine? axisLine,
    AxisLabel? axisLabel,
    AxisTick? axisTick,
    SplitLine? splitLine,
    SplitArea? splitArea,
    AxisPointer? axisPointer,
  }) {
    return YAxis(
      position: position ?? this.position,
      offset: offset ?? this.offset,
      show: show ?? this.show,
      type: type ?? this.type,
      categoryList: categoryList ?? this.categoryList,
      categoryCenter: categoryCenter ?? this.categoryCenter,
      alignTicks: alignTicks ?? this.alignTicks,
      timeType: timeType ?? this.timeType,
      timeRange: timeRange ?? this.timeRange,
      min: min ?? this.min,
      max: max ?? this.max,
      splitNumber: splitNumber ?? this.splitNumber,
      minInterval: minInterval ?? this.minInterval,
      maxInterval: maxInterval ?? this.maxInterval,
      interval: interval ?? this.interval,
      logBase: logBase ?? this.logBase,
      inverse: inverse ?? this.inverse,
      axisName: axisName ?? this.axisName,
      axisLine: axisLine ?? this.axisLine,
      axisLabel: axisLabel ?? this.axisLabel,
      axisTick: axisTick ?? this.axisTick,
      splitLine: splitLine ?? this.splitLine,
      splitArea: splitArea ?? this.splitArea,
    );
  }
}
